site_name: ETH - Summaries for CS
site_url: https://baeriswyln.github.io/eth-cs/
theme: 
    name: material
    palette:
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: custom
        accent: custom
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: custom
        accent: custom
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
    features:
      - navigation.instant
      - navigation.tabs
      - navigation.top
      - navigation.indexes
      - navigation.footer
      - search.suggest
      - search.highlight
nav:
  - Welcome:
    - index.md
  - Bachelors:
    - bachelors/index.md
    - Linear Algebra:
      - bachelors/la/index.md
    - Algorithms and Datastructures:
      - bachelors/ads/index.md
    - Theoretical Computer Science:
      - bachelors/tcs/index.md
      - Languages: bachelors/tcs/languages.md
      - Finite-State Machine: bachelors/tcs/fsm.md
      - Computability: bachelors/tcs/computability.md
  - Security:
    - security/index.md
    - Zero-Knowledge Proof:
      - security/zkp/index.md
      - Intro and definitions: security/zkp/intro-definitions.md
      - Sigma Protocols: security/zkp/sigma.md
      - Arguments and proofs: security/zkp/zk-arguments-and-proofs.md
      - Non-interactive Zero Knowledge: security/zkp/non-interactive-zk.md
  - Data:
    - data/index.md
    - Reliable and Trustworthy AI:
      - data/rtai/index.md
      - Robustness: data/rtai/robustness.md
      - Privacy: data/rtai/privacy.md
      - Fairness/Bias: data/rtai/fairness-bias.md
  - General:
    - general/index.md
    - Placeholder:
      - general/placeholder/index.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/baeriswyln
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nicolas-baeriswyl/
copyright: Copyright &copy; 2023 - 2023 Nicolas Baeriswyl
repo_url: https://github.com/baeriswyln/eth-cs
repo_name: baeriswyln/eth-cs
markdown_extensions:
  - footnotes
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
        generic: true
plugins:
  - search
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css